/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders/index'
import { Route as AuthedProductsNewRouteImport } from './routes/_authed/products/new'
import { Route as AuthedProductsProductIdRouteImport } from './routes/_authed/products/$productId'
import { Route as AuthedOrdersOrderIdRouteImport } from './routes/_authed/orders/$orderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsProductIdRoute = AuthedProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersOrderIdRoute = AuthedOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/products/$productId': typeof AuthedProductsProductIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/products/$productId': typeof AuthedProductsProductIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/products': typeof AuthedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/_authed/products/$productId': typeof AuthedProductsProductIdRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/products/new'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/orders/$orderId'
    | '/_authed/products/$productId'
    | '/_authed/products/new'
    | '/_authed/orders/'
    | '/_authed/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$productId': {
      id: '/_authed/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthedProductsProductIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/$orderId': {
      id: '/_authed/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthedOrdersOrderIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrdersOrderIdRoute: typeof AuthedOrdersOrderIdRoute
  AuthedProductsProductIdRoute: typeof AuthedProductsProductIdRoute
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrdersOrderIdRoute: AuthedOrdersOrderIdRoute,
  AuthedProductsProductIdRoute: AuthedProductsProductIdRoute,
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
